namespace ValourChain.Models;

public enum NodeTyle
{
    Validator,
    FullNode,
    LightNode
}

public class Node
{
    /// <summary>
    /// An ID used to identify other nodes internally. Generated by this client.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();
    
    /// <summary>
    /// The location of a node is where it can be accessed by other nodes.
    /// </summary>
    public required string Location { get; set; }
    
    /// <summary>
    /// The wallet address of a node is where it can receive awards and where credits are staked.
    /// </summary>
    public required string WalletAddress { get; set; }
    
    /// <summary>
    /// The name of a node is for human-readable identification.
    /// </summary>
    public string Name { get; set; } = "Unnamed Node";
    
    /// <summary>
    /// The description of a node is for human-readable information.
    /// </summary>
    public string Description { get; set; } = "A Valour Chain node.";
    
    /// <summary>
    /// The last recorded network latency of the node.
    /// </summary>
    public float Latency { get; set; }
    
    /// <summary>
    /// The last time the node has been communicated with.
    /// </summary>
    public DateTime LastSeen { get; set; }
    
    /// <summary>
    /// If not null, the reason the node has been blocked.
    /// </summary>
    public NodeBlockReason? BlockReason { get; set; }
    
    /// <summary>
    /// True if the node is trusted.
    /// </summary>
    public bool Trusted { get; set; }
}